@startwbs
<style>
wbsDiagram {
  :depth(0) {
    BackgroundColor transparent
    LineColor transparent
    FontColor transparent
  }
}
</style>
*_ dummy
** 記録可能にする項目一覧
*** 前提
**** 睡眠状況、デイリー、週の振り返りがそれぞれ A5 1 枚に収まるように

*** 睡眠状況 (週単位で)
**** 睡眠時間
***** "就寝時間" as s01
***** "起床時間" as s02
***** "途中目覚めた回数と間隔 (記録可能であれば)" as s03
**** "記録形式"
***** "<img src=sleeping.png>" as sall
s01 --> sall #crimson
s02 --> sall #crimson
s03 --> sall #crimson

*** デイリー
**** 体温
**** 血圧 (可能なら)
**** 体重 (可能なら)
**** 食事の回数
***** チェックボックスで
**** 服薬状況
***** チェックボックスで
***** 頓服服用メモ

**** 気になる症状
***** 気分の状態 (主観的な 5 段階評価で)
****** 抑うつ感
****** 希死念慮
****** 焦燥感
****** イライラ感
****** その他気になる症状のメモ (不安感とか)

***** 身体的な状態 (主観的な 5 段階評価で)
****** 倦怠感
****** 動悸
****** その他気になる症状のメモ (不安感とか)

**** その日のメモ(自由記載)

*** 週の振り返り
**** 摂食状態概観
**** 精神症状概観
**** 身体症状概観
**** 服薬状況概観 (困っていることなど)
**** その他医療従事者に伝えておきたいトピックや質問等

@endwbs
